# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dark_knight/ImageProcessing/TrafficSign

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dark_knight/ImageProcessing/TrafficSign

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dark_knight/ImageProcessing/TrafficSign/CMakeFiles /home/dark_knight/ImageProcessing/TrafficSign/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dark_knight/ImageProcessing/TrafficSign/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named traffic_sign

# Build rule for target.
traffic_sign: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 traffic_sign
.PHONY : traffic_sign

# fast build rule for target.
traffic_sign/fast:
	$(MAKE) -f CMakeFiles/traffic_sign.dir/build.make CMakeFiles/traffic_sign.dir/build
.PHONY : traffic_sign/fast

#=============================================================================
# Target rules for targets named tsr

# Build rule for target.
tsr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsr
.PHONY : tsr

# fast build rule for target.
tsr/fast:
	$(MAKE) -f CMakeFiles/tsr.dir/build.make CMakeFiles/tsr.dir/build
.PHONY : tsr/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/traffic_sign.dir/build.make CMakeFiles/traffic_sign.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/traffic_sign.dir/build.make CMakeFiles/traffic_sign.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/traffic_sign.dir/build.make CMakeFiles/traffic_sign.dir/main.cpp.s
.PHONY : main.cpp.s

test1.o: test1.cpp.o

.PHONY : test1.o

# target to build an object file
test1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.o
.PHONY : test1.cpp.o

test1.i: test1.cpp.i

.PHONY : test1.i

# target to preprocess a source file
test1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.i
.PHONY : test1.cpp.i

test1.s: test1.cpp.s

.PHONY : test1.s

# target to generate assembly for a file
test1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.s
.PHONY : test1.cpp.s

traffic_sign.o: traffic_sign.cpp.o

.PHONY : traffic_sign.o

# target to build an object file
traffic_sign.cpp.o:
	$(MAKE) -f CMakeFiles/tsr.dir/build.make CMakeFiles/tsr.dir/traffic_sign.cpp.o
.PHONY : traffic_sign.cpp.o

traffic_sign.i: traffic_sign.cpp.i

.PHONY : traffic_sign.i

# target to preprocess a source file
traffic_sign.cpp.i:
	$(MAKE) -f CMakeFiles/tsr.dir/build.make CMakeFiles/tsr.dir/traffic_sign.cpp.i
.PHONY : traffic_sign.cpp.i

traffic_sign.s: traffic_sign.cpp.s

.PHONY : traffic_sign.s

# target to generate assembly for a file
traffic_sign.cpp.s:
	$(MAKE) -f CMakeFiles/tsr.dir/build.make CMakeFiles/tsr.dir/traffic_sign.cpp.s
.PHONY : traffic_sign.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... traffic_sign"
	@echo "... tsr"
	@echo "... rebuild_cache"
	@echo "... test1"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test1.o"
	@echo "... test1.i"
	@echo "... test1.s"
	@echo "... traffic_sign.o"
	@echo "... traffic_sign.i"
	@echo "... traffic_sign.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

